{
  "formatVersion": "1.1",
  "component": {
    "group": "ilya.project",
    "module": "logging-starter",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-0.0.1-SNAPSHOT.jar",
          "url": "logging-starter-0.0.1-SNAPSHOT.jar",
          "size": 16519,
          "sha512": "023cde30c4aebef2a317bacc6b39d088875198ec6b23875039852868cb92d21d08bb19b4032ba661f0f375ce2c9ba7a9c350164ad5fad25db8d0581a6ca92ee8",
          "sha256": "000abd0ffe8be67cad10f991cd14133429037ead9e75ecb5343484f40e3b02a9",
          "sha1": "8e93c4eb0954d24c5f3a75640606e836edde4396",
          "md5": "e331e188788b103465ee5ceda0cb8916"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-parent",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-0.0.1-SNAPSHOT.jar",
          "url": "logging-starter-0.0.1-SNAPSHOT.jar",
          "size": 16519,
          "sha512": "023cde30c4aebef2a317bacc6b39d088875198ec6b23875039852868cb92d21d08bb19b4032ba661f0f375ce2c9ba7a9c350164ad5fad25db8d0581a6ca92ee8",
          "sha256": "000abd0ffe8be67cad10f991cd14133429037ead9e75ecb5343484f40e3b02a9",
          "sha1": "8e93c4eb0954d24c5f3a75640606e836edde4396",
          "md5": "e331e188788b103465ee5ceda0cb8916"
        }
      ]
    }
  ]
}
