{
  "formatVersion": "1.1",
  "component": {
    "group": "ilya.project",
    "module": "logging-starter",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-0.0.1-SNAPSHOT.jar",
          "url": "logging-starter-0.0.1-SNAPSHOT.jar",
          "size": 1453,
          "sha512": "d43d00eb1f00deccbe735efe09a5699eaec8133adf6332a0ff363c33dce67653f744b5f005dc6e6845da21fcb405cdca5db9ea64cc5658b2a066c138220ed95e",
          "sha256": "50499d9f72d31b8c4e5ae9c94ef0c8fa09744d66170ebaf94f2f5035793d7841",
          "sha1": "e5a6d5113fe7c1667a2ae4e1db91757f7b861c57",
          "md5": "34af9f5a36ed5982b835f7d39c69b56a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-parent",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-0.0.1-SNAPSHOT.jar",
          "url": "logging-starter-0.0.1-SNAPSHOT.jar",
          "size": 1453,
          "sha512": "d43d00eb1f00deccbe735efe09a5699eaec8133adf6332a0ff363c33dce67653f744b5f005dc6e6845da21fcb405cdca5db9ea64cc5658b2a066c138220ed95e",
          "sha256": "50499d9f72d31b8c4e5ae9c94ef0c8fa09744d66170ebaf94f2f5035793d7841",
          "sha1": "e5a6d5113fe7c1667a2ae4e1db91757f7b861c57",
          "md5": "34af9f5a36ed5982b835f7d39c69b56a"
        }
      ]
    }
  ]
}
